media:
  input: docs/files/media
  output: /docs/files/media
content:
  - name: articles
    label: Articles
    path: docs/files/_articles
    type: collection
    fields: 
      - name: author
        label: Author
        type: select
        options:
          values:
          - value: attie
            label: Attie Retief
          - value: heidi
            label: Heidi Malherbe
          - value: carel
            label: Carel de Beer
          - value: jacoline
            label: Jacoline Kritzinger
          - value: janherman
            label: Jan-Herman Troskie
          - value: nadine
            label: Nadine van Aswegen
      - name: date
        label: Date
        type: date
        options:
          format: yyyy-mm-dd
      - name: articleType
        label: Article Type
        type: select
        options:
          values:
          - value: overview
            label: Overview
          - value: guide
            label: Guide
      - name: area
        label: Area
        type: select
        options:
          values:
            - value:  ArrivalQC
            - value:  BuildUps
            - value:  ChargeAssignments
            - value:  Claims
            - value:  ContainerConfirmations
            - value:  FreightAllocations
            - value:  LogisticsDocuments
            - value:  LogisticsWorkflow
            - value:  MasterData
            - value:  PalletChargeStandards
            - value:  PalletEditor
            - value:  PalletFiles
            - value:  PalletProduction
            - value:  PalletStock
            - value:  PalletVerification
            - value:  PalletWizard
            - value:  PredepartureQC
            - value:  ProduceAccounting
            - value:  ProduceBills
            - value:  ProduceOrderConfirmations
            - value:  ProduceOrders
            - value:  ProduceTrades
            - value:  ReinspectionQC
            - value:  Reporting
            - value:  SalesAllocations
      - name: title
        label: Title
        type: string
      - name: nav_order
        label: Navigation Order
        type: number
      - name: has_children
        label: Has Children
        type: boolean
      - name: parent
        label: Parent
        type: string
      - name: nav_exclude
        label: Exclude from navigation
        type: boolean
      - name: has_toc
        label: Generate Table of Contents
        type: boolean
      - name: body
        label: Body
        type: rich-text

