media:
  input: docs/media
  output: docs/media
content:
  - name: home
    label: Home
    path: docs/index.md
    type: file
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
  - name: articles
    label: Articles
    path: docs/articles
    filename: '{title}.md'
    type: collection
    view:
      fields: [ title ]
      primary: title
      sort: [ title ]
      default:
        search: 'title'
        sort: title
        order: asc
    fields: 
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
  - name: structure
    label: Structure
    path: structure.json
    type: file

