media:
  input: docs/files/media
  output: /docs/files/media
content:
  - name: articles
    label: Articles
    path: docs/files/_articles
    filename: '{nav_order} - {title}.md'
    type: collection
    view:
      fields: [ order, section, area, title, author, date ]
      primary: title
      sort: [ order, section, area ]
      default:
        search: 'section, title, author, area'
        sort: order, section, area
        order: asc
    fields: 
      - name: author
        label: Author
        type: select
        options:
          values:
          - value: attie
            label: Attie Retief
          - value: heidi
            label: Heidi Malherbe
          - value: carel
            label: Carel de Beer
          - value: jacoline
            label: Jacoline Kritzinger
          - value: janherman
            label: Jan-Herman Troskie
          - value: nadine
            label: Nadine van Aswegen
      - name: date
        label: Date
        type: date
        options:
          format: yyyy-mm-dd
      - name: title
        label: Title
        type: string
      - name: draft
        label: Draft
        type: boolean
      - name: body
        label: Body
        type: rich-text

