media:
  input: docs/files/media
  output: /docs/files/media
content:
  - name: home
    label: Home
    path: docs/index.md
    type: file
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
  - name: articles
    label: Articles
    path: docs/files/articles
    filename: '{title}.md'
    type: collection
    view:
      fields: [ title, author, date ]
      primary: title
      sort: [ title, author, date ]
      default:
        search: 'title, author, date'
        sort: title, author, dat
        order: asc
    fields: 
      - name: author
        label: Author
        type: select
        options:
          values:
          - value: attie
            label: Attie Retief
          - value: heidi
            label: Heidi Malherbe
          - value: carel
            label: Carel de Beer
          - value: jacoline
            label: Jacoline Kritzinger
          - value: janherman
            label: Jan-Herman Troskie
          - value: nadine
            label: Nadine van Aswegen
      - name: date
        label: Date
        type: date
        options:
          format: yyyy-mm-dd
      - name: title
        label: Title
        type: string
      - name: draft
        label: Draft
        type: boolean
      - name: body
        label: Body
        type: rich-text
  - name: structure
    label: Structure
    path: structure.json
    type: file

