title: ProduceLinc Knowledge Base
remote_theme: just-the-docs/just-the-docs
color_scheme: producelinc
logo: "assets/images/producelinc.png"
favicon_ico: "assets/images/producelinc.ico"
callouts_level: loud

callouts:
  overview:
    title: Overview
    color: blue
  documentation:
    title: Documentation
    color: green
  guides:
    title: Guides
    color: yellow

titles_from_headings:
  enabled:     false
  strip_title: false
  collections: false

